version: "3.3"

services:
  petoria-api:
    container_name: petoria-api
    restart: always
    image: node:20.19.0
    ports:
      - 3002:3002
    volumes:
      - ./:/usr/src/petoria
    working_dir: /usr/src/petoria
    networks:
      - monorepo-network
    command: bash -c "npm install && npm run build && npm run start:prod"

  petoria-batch:
    container_name: petoria-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/petoria
      - ./uploads:/app/uploads
    working_dir: /usr/src/petoria
    networks:
      - monorepo-network
    command: bash -c "npm install && npm run build:batch && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge
