
services:
  petoria-api:
    container_name: petoria-api
    restart: always
    image: node:20.10.0
    ports:
      - 4001:3007
    volumes:
      - ./:/usr/src/petoria
    working_dir: /usr/src/petoria
    networks:
      - monorepo-network
    command: bash -c "rm -fr dist && npm install && npm run build && npm run start:prod"

  petoria-batch:
    container_name: petoria-batch
    restart: unless-stopped
    image: node:20.10.0
    ports:
      - 4002:3008
    volumes:
      - ./:/usr/src/petoria
      - ./uploads:/app/uploads
    working_dir: /usr/src/petoria
    networks:
      - monorepo-network
    command: bash -c "npm install && npm run build:batch && npm run start:prod:batch"

networks:
  monorepo-network:
    driver: bridge


# petoria-next： localhost: 4000 <=> container: 3000
# petoria-api:   localhost: 4001 <=> container: 3007
# petoria-batch: localhost:4002 <=> container: 3008